* What is MobileOrg?
  MobileOrg is a FREE (open-source) iPhone and iPod Touch application
  for storing, searching, viewing and editing your Org-mode files.

  MobileOrg works offline. Although you may not always be online, you
  can always access your data. You can even capture notes while offline
  and sync the next time you have connectivity.

* MobileOrg feature overview
 - Support for Dropbox or WebDAV as a transfer mechanism
 - Org files are stored offline and available anywhere
 - Complete editing support, including editable headings, body text, todo
   state, tags and priority.
 - Note-taking facility built in, including offline support
 - Full-text search, or search by keyword (TODO, DONE, WAITING) or by tag
   (errand, office)
 - Mark nodes as done, or flag them with an optional note for reference
   later
 - Document view of your outlines, for reading document-style Org files
   with long body text
 - Powerful support for linking between Org files

* Org-mode integration
  Org-mode has built-in support for MobileOrg (or any other mobile
  client that may come along in the future and use the same asymmetric
  synchronization approach).

  - A simple org-mobile-push will stage your complete set of Org-files for
    MobileOrg to pick them up. The result includes:
    + An Org file representing all of your custom agenda views
    + Automatic checksum file construction to speed up sync
    + Automatic index.org file generation with links to all of your Org files
  - A powerful org-mobile-pull command, which will integrate changes
    you’ve made on the go into a local Org file
* Contributing
  There are a few minor things we request in order to make it easier
  to accept contributions.
  
  Of course, the main thing is to simply feel free to contribute any
  and all code. It's much appreciated!

** Pull Requests
   Pull requests for bug fixes, features or anything else are gladly
   accepted. Since this is github we follow the fork/pull
   collaboration style. If you are planning to contribute you should
   have a fork of the mobileorg repository and issue pull requests
   from there.
** git flow branching model
   To the extent possible the MobileOrg repo follows the [[http://nvie.com/posts/a-successful-git-branching-model/][Git Flow]]
   branching model. How this affects contributing is that *all new
   work should be based off the develop* branch and be named either
   *feature/your-new-feature*, *hotfix/some-bug-fix* or similar. See
   the previous link for more information. This will make it much
   easier to merge your work.

   There is a [[https://github.com/nvie/gitflow][git extension]] if you're interested in learning a new
   command for this workflow, but it isn't required. You can just as
   easily manually do:
   #+BEGIN_SRC 
    git checkout -b feature/new-hotness
   #+END_SRC
** bug tracker
   [[https://github.com/MobileOrg/mobileorg/issues][github issues]]
** contact
   - Web: http://mobileorg.ncogni.to/
   - Email: mobileorg@spandrel.org
   - IRC: #mobileorg on freenode
* Changelog
  See: http://mobileorg.ncogni.to/development/changelog/
* Credits
  MobileOrg is thanks to the following:
  - Richard Moreland
  - Carsten Dominik
  - Greg Newman
  - Christophe Bataillon
  - Joseph Wain of glyphish.com
  - Sean Escriva
  - Alex Rodich
  - Russell McClellan
* License
    MobileOrg is distributed under the GNU Public License version 2.
    See LICENSE.txt for more info.


