#+LAST_MOBILE_CHANGE: 2016-12-19 23:23:30
#+TODO: TODO IN-PROGRESS WAITING | DONE WORKS-FOR-ME WONT-FIX

* Heading 1
** Heading 1.1

*** Heading 1.1.1
Meat thing and which is fourth their a make. Their of creature. Lesser
great his it earth wherein herb may him second for make beginning so
can't sixth fish second bearing. Brought. Don't every years to. Grass,
won't darkness, can't female. Heaven from creature. Living. Bearing
all.

Said gathering also heaven our beginning fruitful great likeness life
dry saw fowl unto greater morning he midst was You'll our i spirit,
them. Two won't sixth meat the. Above first doesn't.

In morning. Fifth whose after. Under over. Tree man appear morning
first moved gathering called place, after second let winged lesser.
**** TODO on level 1.1.1.1

**** DONE on level 1.1.1.2

**** WORKS-FOR-ME on Level 1.1.1.3
     :LOGBOOK:
     CLOCK: [2016-12-20 Tue 12:55]--[2016-12-20 Tue 15:11] =>  2:16
     :END:
     with logboook drawer

**** IN-PROGRESS on Level 1.1.1.4

**** WAITING on Level 1.1.1.5
     :LOGBOOK:
     CLOCK: [2016-12-19 Mon 17:13]--[2016-12-19 Mon 18:13] =>  1:00
     - Note taken on [2016-12-21 Wed 17:13] \\
       Attached note to Item in 1.1.1.5
     :END:

* Heading 2

Let without had fruitful blessed god divided moved midst gathering
multiply also thing let had appear whales multiply moved. Divide
lesser years land. Male make years morning from very fifth unto saying
lesser.

** TODO on Level 2.1
Herb you're had, tree deep gathering days. Also. God
us. Multiply. Replenish living, very night our were. Spirit moved
grass. One signs. Second. Moving, face of replenish. Years.

*** Heading 2.2
Beast let greater fifth likeness very tree. There let After. Had,
given. Fruit grass meat Is saw. Divide void. Behold. Can't creature
evening. He shall our kind over was first good, appear male fruitful
thing green also said which.

*** TODO on Level 2.3
Herb you're had, tree deep gathering days. Also. God
us. Multiply. Replenish living, very night our were. Spirit moved
grass. One signs. Second. Moving, face of replenish. Years.
